Does not depend on ts-node
Both of the following did not work, so I gave up.
Also, ts-node was not much needed.

```
ts-node-esm src/index.ts
ReferenceError: exports is not defined in ES module scope
    at file:///Users/kjirou/projects/rosenkoenig-core/src/index.ts:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

```
node --loader ts-node/esm --inspect ./src/index.ts
Debugger listening on ws://127.0.0.1:9229/d9104229-b809-419a-9779-15329c439474
For help, see: https://nodejs.org/en/docs/inspector
(node:2851) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReferenceError: exports is not defined in ES module scope
    at file:///Users/kjirou/projects/rosenkoenig-core/src/index.ts:2:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```